### ISSUE TITLE
Ripgrep crashes

### ISSUE THREAD

**Issue by emizzle** [vidovichb/minimalTODO#1]
Hi, i love this extension, well done! I've recently upgraded computers, and this extension was working great on my old compputer, but not on the new one. I am not on macos 13.2.1 and experiencing ripgrep crashing:

```shell
2023-03-15 16:26:55.138 [error] Error: Ripgrep crashed due to unexpected error.
	at RipgrepService.findMatches (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.2/out/services/ripgrep-execution-service.js:29:19)
	at MainStructureResolver.executeScan (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.2/out/providers/main-tree-view-provider/main-structure-resolver.js:41:36)
	at /Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.2/out/providers/main-tree-view-provider/main-structure-resolver.js:45:77
	at Array.map (<anonymous>)
	at MainStructureResolver.ripgrepScan (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.2/out/providers/main-tree-view-provider/main-structure-resolver.js:45:59)
	at new MainStructureResolver (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.2/out/providers/main-tree-view-provider/main-structure-resolver.js:15:14)
	at activate (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.2/out/extension.js:22:35)
	at Ui.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14833)
	at Ui.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14532)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12550
	at async f.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
```

I've tried installing ripgrep via brew (ensuring it was in my path) and npm (globally), but neither worked. Any ideas?

**Comment by vidovicblaz19** [comment]
Hi, I'm glad to hear you find the extension helpful. As for the problem you are experiencing, I am not quite sure what could be causing it. The extension uses own ripgrep executable, which it fetches using https://github.com/microsoft/vscode-ripgrep as a dependency. Therefore ripgrep in path or installed globally via npm will always be ignored by extension. To ease the process of pinpointing the problem, I will improve the error logging a bit. "Ripgrep crashed due to unexpected error." was a quick and temporary way to handle it.

**Comment by emizzle** [comment]
I'm not sure if you've updated the error info, but now I'm seeing:
```
2023-03-16 12:00:12.095 [error] TypeError: Cannot read properties of null (reading 'endsWith')
	at RipgrepService.findMatches (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/out/services/ripgrep-execution-service.js:30:79)
	at MainStructureResolver.executeScan (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/out/providers/main-tree-view-provider/main-structure-resolver.js:41:36)
	at /Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/out/providers/main-tree-view-provider/main-structure-resolver.js:45:77
	at Array.map (<anonymous>)
	at MainStructureResolver.ripgrepScan (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/out/providers/main-tree-view-provider/main-structure-resolver.js:45:59)
	at new MainStructureResolver (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/out/providers/main-tree-view-provider/main-structure-resolver.js:15:14)
	at activate (/Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/out/extension.js:23:35)
	at Ui.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14833)
	at Ui.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14532)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12550
	at async f.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
	```

**Comment by emizzle** [comment]
Debugging my local instance, i was able to extract `ripgrep.error`:
```shell
2023-03-16 12:07:33.502 [error] Error: Ripgrep.error: Error: spawnSync /Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4/node_modules/@vscode/ripgrep/bin/rg Unknown system error -8
```

**Comment by emizzle** [comment]
Seems that the error usually has to do with trying to run a binary that is built for the wrong arch. I'm running arm64 on an M2. Locally, I was able to npm install and run [`@vscode/ripgrep`](https://www.npmjs.com/package/@vscode/ripgrep):
```shell
❯ npm install @vscode/ripgrep

added 6 packages, and audited 7 packages in 3s

found 0 vulnerabilities
❯ cd node_modules/@vscode/ripgrep/bin
❯ ./rg --help
ripgrep 13.0.0
Andrew Gallant <jamslam@gmail.com>

ripgrep (rg) recursively searches the current directory for a regex pattern.
By default, ripgrep will respect gitignore rules and automatically skip hidden
files/directories and binary files.

Use -h for short descriptions and --help for more details.

Project home page: https://github.com/BurntSushi/ripgrep


USAGE:
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] -e PATTERN ... [PATH ...]
    rg [OPTIONS] -f PATTERNFILE ... [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN
    rg [OPTIONS] --help
    rg [OPTIONS] --version
    
    ....
```

So there is definitely a build available for my current arch. Not sure if possibly the extension is somehow installing the wrong arch (although looking at the package.json, it appears to be a pretty stock standard way of installing).

**Comment by vidovicblaz19** [comment]
I think i have found the problem and will fix it over the weekend when I will have more time. node_modules seem to be packaged incorrectly, they contain only ripgrep executable for windows. Temporary fix is:
Go to directory where the extension is installed, that would be 
```
.../Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4
```
in your case.

In this directory delete node_modules. And reinstall modules.
```
npm i --omit=dev
```
It should grab correct ripgrep, respecting the os of choice.

**Comment by emizzle** [comment]
```
npm i --omit=dev
```
didn't work. I had to uninstall then install:
```
cd /Users/egonat/.vscode/extensions/vidovichb.minimaltodo-1.0.4
npm uninstall @vscode/ripgrep
npm i @vscode/ripgrep
```

Now the extension works 💪

**Comment by vidovicblaz19** [comment]
Glad to hear that, will provide a more permanent solution soon. ✌️

**Comment by vidovicblaz19** [comment]
Ripgrep cross-platform support improved in pull request https://github.com/vidovichb/minimalTODO/pull/3.
